### ISSUE TITLE
Clarification for "Artifact boost boost bonus"

### ISSUE THREAD

**Issue by BenMQ** [SaladFork/egg-inc-tools#2]
Is the "Artifact boost boost bonus" intended for the Dilithium Monocles? The current number seems off. 

Example input: 48M target population 1000 IHR, 0% bonus.

The CW row gives 48M total population.

Now if we set the bonus to 10% I would have expected the IHR to grow by 10% and therefore the total projected population to go up by 10%, 48*1.1 = 52.8M. However the tool returns 50.4M.

**Comment by BenMQ** [comment]
Here's an in-game example: 

Base IHR: 4440. 

After turning on 100x tachyon and 2x boost beacon, the IHR increases by 200x to 888k.
https://imgur.com/a/zaDx23L

With a 10% dilithium monocle equipted, the IHR increases by a flat 10% to 976.8k

https://imgur.com/a/CqKT3qg

I can send in a PR if this should be the intended value. Or if I'm interpreting the input field wrong, a clarification would be great, thanks!

**Comment by BenMQ** [comment]
Hi SaladFork hope you are doing well! Wondering if you are still playing the game or interested in maintaining this great tool. If not, would you be interested in letting me update it, or open source it and let me fork it to keep it updated?

Thanks!

**Comment by SaladFork** [comment]
Thank you for the ping! I had somehow disabled GitHub notifications so missed your comments/PRs. Luckily someone reached out on Discord to let me know. I believe I've fixed the notifications...

> The current number seems off.
> Example input: 48M target population 1000 IHR, 0% bonus.
> The CW row gives 48M total population.
> Now if we set the bonus to 10% I would have expected the IHR to grow by 10% and therefore the total projected population to go up by 10%, 48*1.1 = 52.8M. However the tool returns 50.4M.

Hmm, interestingly the CC combo returns the expected value (52.8M) but CW does not, though a W Boost Beacon is a 2x that lasts the full duration of a C Powerful Tachyon Prism, so should be equivalent. Definitely seems to be a bug here.

> Is the "Artifact boost boost bonus" intended for the Dilithium Monocles?

It's meant to represent any "boost boost" type bonuses (this is how it is phrased in-game). Right now that's just provided by Boost Beacons and Dilithium Monocles, so I'm fine with making things clearer. If we know it is only one item, I wonder if there is a nicer UI we can show for it (select your monocle, select a rarity? slider with steps at possible values?) 🤔.

> Base IHR: 4440.
> After turning on 100x tachyon and 2x boost beacon, the IHR increases by 200x to 888k.
> With a 10% dilithium monocle equipted, the IHR increases by a flat 10% to 976.8k

This in-game example was helpful, thanks!

[The bug](https://github.com/SaladFork/egg-inc-tools/blob/a68335dc1dba3eb6da418c2d5d3f940b61eeb7d4/src/app/utils/boosts.js#L206) seems to be caused by assuming that the effect of a Boost Boost artifact (Dilithium Monocle) is additive with other Boost Beacons (e.g. a 2x Boost Beacon and a 10% dilithium = 2.1x overall multiplier) rather than further multiplicative (2x boost beacon and a 10% monocle = 2.2x overall multiplier).

Using the example from above, here's the calculation with the incorrect assumption:
```
IHR * Hatcheries * Minutes * InternalHatcheryCalm * Multipliers(Prisms*(BoostBeacon+ArtifactBoostBoost)) = Hatched
1000 * 4 * 20 * 3 * (100*(2+.1)) = 50.4M
```

And what it should be:
```
IHR * Hatcheries * Minutes * InternalHatcheryCalm * Prisms * Boost Beacon Multiplier * Artifact Boost Boost Multiplier = Hatched
1000 * 4 * 20 * 3 * (100*2) * 1.1 = 52.8M
```

I don't like my time-slicing approach to calculating final chickens hatched, especially as it makes it more difficult to factor in things like boost duration bonus, so am very interested in your proposed alternative.

**Comment by SaladFork** [comment]
I've push a quick fix for this issue (and deployed it alongside the changes from the other PR), but let's continue discussion in the PR (#3) as to the better approach to calculating hatches.

Thanks again!

**Comment by BenMQ** [comment]
Thanks for the quick update and the detailed response! I'll find time to clean up the proposed change in #3 this week and we can continue there 😄
